<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Vocabia.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Seed\Resources\de_en_pilot.json" LogicalName="Vocabia.Core.Seed.Resources.de_en_pilot.json" />
  </ItemGroup>

</Project>
